spring:
  application:
    name: github-profile-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/github-profile-manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

github:
  url: https://api.github.com/users